import type { Metadata } from 'next'
import { NavBar } from '../components/Navbar'
import { MessageCard } from '../components/MessageCard'
import { Modal } from '../components/Modal'
import { Switch } from '../components/Switch'
// import '../globals.css'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
